import { defineConfig } from 'wxt'

export default defineConfig({
  modules: ['@wxt-dev/module-vue'],
  srcDir: 'src',
  manifest: {
    name: 'Shortkeys (Custom Keyboard Shortcuts)',
    short_name: 'Shortkeys',
    description: 'Custom keyboard shortcuts for your browser',
    version: '5.0.0',
    default_locale: 'en',
    browser_specific_settings: {
      gecko: {
        id: 'niceshortcuts@niceshortcuts.com',
        strict_min_version: '109.0',
      },
    },
    icons: {
      16: '/images/icon_16.png',
      48: '/images/icon_48.png',
      128: '/images/icon_128.png',
    },
    action: {
      default_icon: {
        16: '/images/icon_16.png',
        48: '/images/icon_48.png',
        128: '/images/icon_128.png',
      },
    },
    commands: {
      // TABS
      '01-newtab': { description: 'TABS: New tab' },
      '02-closetab': { description: 'TABS: Close tab' },
      '03-nexttab': { description: 'TABS: Next tab' },
      '04-prevtab': { description: 'TABS: Previous tab' },
      '05-togglepin': { description: 'TABS: Pin/unpin tab' },
      '06-togglemute': { description: 'TABS: Mute/unmute tab' },
      '07-onlytab': { description: 'TABS: Close other tabs' },
      '08-closelefttabs': { description: 'TABS: Close tabs to the left' },
      '09-closerighttabs': { description: 'TABS: Close tabs to the right' },
      '10-closeduplicatetabs': { description: 'TABS: Close duplicate tabs' },
      '11-clonetab': { description: 'TABS: Duplicate tab' },
      '12-movetabtonewwindow': { description: 'TABS: Move tab to new window' },
      '13-reopentab': { description: 'TABS: Reopen closed tab' },
      '14-firsttab': { description: 'TABS: First tab' },
      '15-lasttab': { description: 'TABS: Last tab' },
      '16-lastusedtab': { description: 'TABS: Switch to last used tab' },
      '17-movetableft': { description: 'TABS: Move tab to the left' },
      '18-movetabright': { description: 'TABS: Move tab to the right' },
      '19-movetabtofirst': { description: 'TABS: Move tab to first position' },
      '20-movetabtolast': { description: 'TABS: Move tab to last position' },
      '21-sorttabs': { description: 'TABS: Sort tabs alphabetically by title' },
      '22-discardtab': { description: 'TABS: Suspend tab (free memory)' },
      // WINDOWS
      '23-newwindow': { description: 'WINDOWS: New window' },
      '24-newprivatewindow': { description: 'WINDOWS: New private window' },
      '25-closewindow': { description: 'WINDOWS: Close window' },
      '26-fullscreen': { description: 'WINDOWS: Toggle fullscreen' },
      // ZOOMING
      '27-zoomin': { description: 'ZOOMING: Zoom in' },
      '28-zoomout': { description: 'ZOOMING: Zoom out' },
      '29-zoomreset': { description: 'ZOOMING: Zoom reset' },
      // LOCATION
      '30-back': { description: 'LOCATION: Go back' },
      '31-forward': { description: 'LOCATION: Go forward' },
      '32-reload': { description: 'LOCATION: Reload' },
      '33-hardreload': { description: 'LOCATION: Hard reload (bypass cache)' },
      '34-copyurl': { description: 'LOCATION: Copy URL to clipboard' },
      '35-copypagetitle': { description: 'LOCATION: Copy page title' },
      '36-copytitleurl': { description: 'LOCATION: Copy title and URL' },
      '37-copytitleurlmarkdown': { description: 'LOCATION: Copy as markdown link [title](url)' },
      '38-openclipboardurl': { description: 'LOCATION: Open URL from clipboard' },
      '39-openclipboardurlnewtab': { description: 'LOCATION: Open URL from clipboard in new tab' },
      '40-searchgoogle': { description: 'LOCATION: Search Google for selected text' },
      '41-opensettings': { description: 'LOCATION: Open Settings Page' },
      '42-openextensions': { description: 'LOCATION: Open Extensions Page' },
      '43-openshortcuts': { description: 'LOCATION: Open Keyboard Shortcuts Page' },
      // SCROLLING
      '44-top': { description: 'SCROLLING: Scroll to top' },
      '45-bottom': { description: 'SCROLLING: Scroll to bottom' },
      '46-scrolldown': { description: 'SCROLLING: Scroll down' },
      '47-scrolldownmore': { description: 'SCROLLING: Scroll down more' },
      '48-pagedown': { description: 'SCROLLING: Page down' },
      '49-scrollup': { description: 'SCROLLING: Scroll up' },
      '50-scrollupmore': { description: 'SCROLLING: Scroll up more' },
      '51-pageup': { description: 'SCROLLING: Page up' },
      '52-scrollright': { description: 'SCROLLING: Scroll right' },
      '53-scrollrightmore': { description: 'SCROLLING: Scroll right more' },
      '54-scrollleft': { description: 'SCROLLING: Scroll left' },
      '55-scrollleftmore': { description: 'SCROLLING: Scroll left more' },
      // UTILITY
      '56-cleardownloads': { description: 'UTILITY: Clear downloads' },
      '57-showlatestdownload': { description: 'UTILITY: Show latest download' },
      '58-viewsource': { description: 'UTILITY: View source' },
      '59-print': { description: 'UTILITY: Print page' },
      '60-togglebookmark': { description: 'UTILITY: Bookmark/unbookmark current page' },
      '61-openincognito': { description: 'UTILITY: Open current page in incognito window' },
      '62-capturescreenshot': { description: 'UTILITY: Capture current viewport screenshot' },
      '63-capturefullsizescreenshot': { description: 'UTILITY: Capture full size screenshot (max 16,348px)' },
      '64-forcecapturefullsizescreenshot': { description: 'UTILITY: Force capture full size screenshot' },
      '65-disable': { description: 'UTILITY: Do nothing (disable browser shortcut)' },
      '66-disable': { description: 'UTILITY: Do nothing (disable browser shortcut)' },
      '67-disable': { description: 'UTILITY: Do nothing (disable browser shortcut)' },
      '68-disable': { description: 'UTILITY: Do nothing (disable browser shortcut)' },
      '69-disable': { description: 'UTILITY: Do nothing (disable browser shortcut)' },
      '70-disable': { description: 'UTILITY: Do nothing (disable browser shortcut)' },
      // VIDEO
      '71-videoplaypause': { description: 'VIDEO: Play/pause' },
      '72-videomute': { description: 'VIDEO: Mute/unmute' },
      '73-videofullscreen': { description: 'VIDEO: Toggle fullscreen' },
      '74-videospeedup': { description: 'VIDEO: Speed up (0.25×)' },
      '75-videospeeddown': { description: 'VIDEO: Slow down (0.25×)' },
      '76-videospeedreset': { description: 'VIDEO: Reset speed to 1×' },
      '77-videoskipforward': { description: 'VIDEO: Skip forward 10s' },
      '78-videoskipback': { description: 'VIDEO: Skip back 10s' },
      // SEARCH
      '79-searchyoutube': { description: 'SEARCH: Search YouTube for selected text' },
      '80-searchwikipedia': { description: 'SEARCH: Search Wikipedia for selected text' },
      '81-searchgithub': { description: 'SEARCH: Search GitHub for selected text' },
      '82-newtabright': { description: 'TABS: New tab to the right' },
      '83-audibletab': { description: 'TABS: Jump to tab playing audio/video' },
      '84-grouptab': { description: 'TABS: Add tab to new group' },
      '85-ungrouptab': { description: 'TABS: Remove tab from group' },
    },
    permissions: [
      'downloads',
      'storage',
      'tabs',
      'clipboardWrite',
      'clipboardRead',
      'browsingData',
      'bookmarks',
      'sessions',
      'management',
      'debugger',
      'scripting',
      'notifications',
      'activeTab',
      'userScripts',
    ],
    host_permissions: ['*://*/*'],
    content_security_policy: {
      extension_pages: "script-src 'self'; object-src 'self'; style-src 'self' 'unsafe-inline'; style-src-elem 'self' 'unsafe-inline' https://cdn.materialdesignicons.com https://cdn.jsdelivr.net;",
    },
  },
})
